apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: tripviewer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    run: tripviewer
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: tripviewer
  name: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      run: tripviewer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tripviewer
    spec:
      containers:
      - image: registryazp5242.azurecr.io/tripviewer:1
        name: tripviewer
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile:8083
        - name: TRIPS_API_ENDPOINT
          value: http://trips:8081
        ports:
        - containerPort: 80
        resources: {}
status: {}
