apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: trips
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    run: trips
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: trips
  name: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      run: trips
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: trips
    spec:
      containers:
      - image: registryazp5242.azurecr.io/trips:1
        name: trips
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: kv
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: kv
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            usepodidentity: "false"
            keyvaultname: "kv-trip-insights"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            keyvaultobjectversions: "1.0"
            resourcegroup: "teamResources"
            subscriptionid: "49c2e1e8-68e1-4027-bfc6-41a0e54dc153"
            tenantid: "5a90cf0b-183a-4130-a49a-7f43ed0b3347"
status: {}
